### ISSUE TITLE
docstore sync rate

### ISSUE THREAD

**Issue by cakenggt** [orbitdb/orbit-db-docstore#6]
Hello,

I am creating an application with a distributed database using this docstore. However, I have noticed that when a new instance is booted up, it seems to either take forever to, or never, sync with already-running instances until someone does a `put`. Is there supposed to be a timed sync event where instances of the docstore attempt to get the newest database among currently-running peers (and what is the time period on that if it exists?), or is it intended that new peers don't get the store until it is modified?

Thanks

**Comment by haadcode** [comment]
Hi @cakenggt, I believe the problems you were experiencing were due to the problems we had with the replication implementation. We have now [re-written the replication](https://github.com/orbitdb/orbit-db/blob/master/CHANGELOG.md#replication) and the peers should start replicating automatically now.

Thanks for reporting this and let us know if you still experience this problem!
